### ISSUE TITLE
Fix typo in "Recources" 😭😭

### ISSUE THREAD

**Issue by MaksymJediOK** [Andrii-Nechiporuk/JetStudyProject#8]
https://github.com/Andrii-Nechiporuk/JetStudyProject/blob/14d3c3f02249ac62067473783927511a0f888a37/JetStudyProject/JetStudyProject.Infrastracture/DTOs/EventDTOs/EventCreateDto.cs#L25

**Comment by Andrii-Nechiporuk** [comment]
АХахахах, криві руки
